services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: Bayt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FSeX4mlz
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  app:
    build:
      context: .
    restart: always
    command: bash -c "wait-for-it db:5432 -- python manage.py collectstatic --noinput && python manage.py makemigrations picheni && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - . ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
volumes:
  backend_postgres_data:
  static_volume:
  media_volume:



